package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.userPasswordDO;

public interface userPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 18 17:41:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 18 17:41:54 CST 2020
     */
    int insert(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 18 17:41:54 CST 2020
     */
    int insertSelective(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 18 17:41:54 CST 2020
     */
    userPasswordDO selectByPrimaryKey(Integer id);
    userPasswordDO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 18 17:41:54 CST 2020
     */
    int updateByPrimaryKeySelective(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Feb 18 17:41:54 CST 2020
     */
    int updateByPrimaryKey(userPasswordDO record);
}